const MAX_RECIPIENTS = 20
const MAX_STYLES = 100
const LOW_STOCK_THRESHOLD = 100
const CRITICAL_STOCK_THRESHOLD = 50
const DEMAND_WINDOW_DAYS = 30
const COVERAGE_DAYS = 21

function cleanList(value, maxItems, maxLength) {
  const items = Array.isArray(value) ? value : String(value || '').split(/[\n,;]+/)
  return [...new Set(items.map((item) => String(item || '').trim()).filter(Boolean))]
    .slice(0, maxItems)
    .map((item) => item.slice(0, maxLength))
}

function normalizeSettings(input = {}) {
  const recipients = cleanList(input.recipients, MAX_RECIPIENTS, 254).map((email) => email.toLowerCase())
  const invalidEmail = recipients.find((email) => !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))
  if (invalidEmail) throw new Error(`Invalid email address: ${invalidEmail}`)
  const styles = cleanList(input.styles, MAX_STYLES, 100).map((style) => style.toUpperCase())
  const sendHour = Number(input.sendHour ?? input.send_hour ?? 9)
  if (!Number.isInteger(sendHour) || sendHour < 0 || sendHour > 23) throw new Error('Send hour must be from 0 to 23')
  return {
    enabled: Boolean(input.enabled),
    recipients,
    styles,
    sendHour,
    timezone: 'America/New_York',
  }
}

function localDateParts(now = new Date(), timezone = 'America/New_York') {
  const parts = Object.fromEntries(new Intl.DateTimeFormat('en-CA', {
    timeZone: timezone,
    year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit',
    hourCycle: 'h23',
  }).formatToParts(now).filter((part) => part.type !== 'literal').map((part) => [part.type, part.value]))
  return { date: `${parts.year}-${parts.month}-${parts.day}`, hour: Number(parts.hour) }
}

function previousDate(date) {
  const value = new Date(`${date}T12:00:00Z`)
  value.setUTCDate(value.getUTCDate() - 1)
  return value.toISOString().slice(0, 10)
}

function shouldSendDailyReport(currentHour, sendHour) {
  return Number(currentHour) >= Number(sendHour)
}

function escapeHtml(value) {
  return String(value ?? '').replace(/[&<>"']/g, (char) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  })[char])
}

function buildInventoryEmail({ reportDate, inventory = [], movements = [] }) {
  const movementMap = new Map(movements.map((row) => [
    `${row.style}\u241f${row.color}\u241f${row.size}`,
    {
      sales: Number(row.sales || 0),
      returns: Number(row.returns || 0),
      sales30: Number(row.sales30 ?? row.sales_30 ?? 0),
    },
  ]))
  const rows = inventory.map((row) => {
    const movement = movementMap.get(`${row.style}\u241f${row.color}\u241f${row.size}`)
      || { sales: 0, returns: 0, sales30: 0 }
    const quantity = Number(row.quantity || 0)
    const dailyAverage = movement.sales30 / DEMAND_WINDOW_DAYS
    const targetStock = Math.ceil(dailyAverage * COVERAGE_DAYS)
    return {
      ...row,
      quantity,
      ...movement,
      dailyAverage,
      targetStock,
      replenishment: Math.max(0, targetStock - quantity),
      net: movement.returns - movement.sales,
    }
  })
  const totals = rows.reduce((sum, row) => ({
    quantity: sum.quantity + row.quantity,
    sales: sum.sales + row.sales,
    returns: sum.returns + row.returns,
    net: sum.net + row.net,
    sales30: sum.sales30 + row.sales30,
    targetStock: sum.targetStock + row.targetStock,
    replenishment: sum.replenishment + row.replenishment,
  }), { quantity: 0, sales: 0, returns: 0, net: 0, sales30: 0, targetStock: 0, replenishment: 0 })
  const bodyRows = rows.map((row) => `<tr><td>${escapeHtml(row.style)}</td><td>${escapeHtml(row.color)}</td><td>${escapeHtml(row.size)}</td><td>${row.quantity}</td><td>${row.sales}</td><td>${row.returns}</td><td>${row.dailyAverage.toFixed(1)}</td><td>${row.targetStock}</td><td>${row.replenishment}</td></tr>`).join('')
  const html = `<!doctype html><html><body style="font-family:Arial,sans-serif;color:#172033"><h2>Daily Inventory Update · ${escapeHtml(reportDate)}</h2><p>Current inventory and a 21-day replenishment target based on average sales over the previous 30 calendar days.</p><table style="border-collapse:collapse;width:100%;font-size:14px"><thead><tr style="background:#eef2ff"><th>Style</th><th>Color</th><th>Size</th><th>On Hand</th><th>Yesterday Sales</th><th>Yesterday Returns</th><th>30-Day Avg/Day</th><th>21-Day Target</th><th>Suggested Replenishment</th></tr></thead><tbody>${bodyRows || '<tr><td colspan="9">No inventory rows found.</td></tr>'}</tbody><tfoot><tr style="font-weight:bold;background:#f8fafc"><td colspan="3">Total</td><td>${totals.quantity}</td><td>${totals.sales}</td><td>${totals.returns}</td><td>${(totals.sales30 / DEMAND_WINDOW_DAYS).toFixed(1)}</td><td>${totals.targetStock}</td><td>${totals.replenishment}</td></tr></tfoot></table><p style="color:#64748b;font-size:12px">Generated by Feiya ERP.</p><style>th,td{border:1px solid #dbe2ea;padding:8px;text-align:left}th{white-space:nowrap}</style></body></html>`
  return { rows, totals, html, subject: `Daily Inventory Update · ${reportDate}` }
}

function safeSheetName(value, usedNames) {
  const base = String(value || 'Style').replace(/[\\/?*[\]:]/g, ' ').replace(/\s+/g, ' ').trim().slice(0, 31) || 'Style'
  let name = base
  let suffix = 2
  while (usedNames.has(name.toLowerCase())) {
    const ending = ` (${suffix++})`
    name = `${base.slice(0, 31 - ending.length)}${ending}`
  }
  usedNames.add(name.toLowerCase())
  return name
}

const SIZE_RANK = new Map([
  ['XXS', 10], ['XS', 20], ['S', 30], ['M', 40], ['L', 50], ['XL', 60], ['XXL', 70],
  ['PS', 110], ['PM', 120], ['PL', 130], ['PXL', 140],
  ['1X', 210], ['1XL', 210], ['2X', 220], ['2XL', 220], ['3X', 230], ['3XL', 230],
  ['4X', 240], ['4XL', 240], ['5X', 250], ['5XL', 250],
])

function compareInventorySizes(a, b) {
  const left = String(a || '').trim().toUpperCase()
  const right = String(b || '').trim().toUpperCase()
  const rank = (SIZE_RANK.get(left) ?? 1000) - (SIZE_RANK.get(right) ?? 1000)
  return rank || left.localeCompare(right, undefined, { numeric: true, sensitivity: 'base' })
}

function sizeHeaderFill(size) {
  const value = String(size || '').trim().toUpperCase()
  if (/^(XXS|XS|S|M|L|XL|XXL)$/.test(value)) return 'FF16A34A'
  if (/^(PS|PM|PL|PXL)$/.test(value)) return 'FF0F766E'
  if (/^[1-9][0-9]*P$/.test(value)) return 'FFD97706'
  if (/^[1-9][0-9]*W$/.test(value)) return 'FFBE185D'
  if (/^[1-9][0-9]*X(L)?$/.test(value)) return 'FF7C3AED'
  if (/^[0-9]+$/.test(value)) return 'FF2563EB'
  return 'FF475569'
}

async function buildInventoryWorkbook(report) {
  const ExcelJS = require('exceljs')
  const workbook = new ExcelJS.Workbook()
  workbook.creator = 'Feiya ERP'
  workbook.created = new Date(`${report.reportDate || new Date().toISOString().slice(0, 10)}T12:00:00Z`)

  const rowsByStyle = new Map()
  for (const row of report.rows || []) {
    const style = String(row.style || '').trim() || 'Unknown Style'
    if (!rowsByStyle.has(style)) rowsByStyle.set(style, [])
    rowsByStyle.get(style).push(row)
  }

  const usedNames = new Set()
  for (const [style, rows] of rowsByStyle) {
    const sheet = workbook.addWorksheet(safeSheetName(style, usedNames), {
      views: [{ state: 'frozen', xSplit: 1, ySplit: 5 }],
      pageSetup: { orientation: 'landscape', fitToPage: true, fitToWidth: 1, fitToHeight: 0 },
    })
    const sizes = [...new Set(rows.map((row) => String(row.size || '').trim()).filter(Boolean))]
      .sort(compareInventorySizes)
    const colorMap = new Map()
    for (const item of rows) {
      const color = String(item.color || '').trim() || 'Unknown Color'
      const key = color.toLocaleLowerCase()
      if (!colorMap.has(key)) colorMap.set(key, { color, bySize: new Map() })
      const group = colorMap.get(key)
      const size = String(item.size || '').trim()
      const existing = group.bySize.get(size) || {
        quantity: 0, sales: 0, returns: 0, sales30: 0,
        dailyAverage: 0, targetStock: 0, replenishment: 0,
      }
      for (const field of ['quantity', 'sales', 'returns', 'sales30']) {
        existing[field] += Number(item[field] || 0)
      }
      existing.dailyAverage = existing.sales30 / DEMAND_WINDOW_DAYS
      existing.targetStock = Math.ceil(existing.dailyAverage * COVERAGE_DAYS)
      existing.replenishment = Math.max(0, existing.targetStock - existing.quantity)
      group.bySize.set(size, existing)
    }
    const colors = [...colorMap.values()].sort((a, b) =>
      a.color.localeCompare(b.color, undefined, { numeric: true, sensitivity: 'base' })
    )
    const blocks = [
      { key: 'quantity', title: 'Current Inventory', fill: 'FF1E3A8A', numFmt: '#,##0' },
      { key: 'sales', title: 'Yesterday Sales', fill: 'FF2563EB', numFmt: '#,##0' },
      { key: 'returns', title: 'Yesterday Returns', fill: 'FF0F766E', numFmt: '#,##0' },
      { key: 'dailyAverage', title: '30-Day Avg / Day', fill: 'FF475569', numFmt: '0.0' },
      { key: 'targetStock', title: '21-Day Target', fill: 'FF7C3AED', numFmt: '#,##0' },
      { key: 'replenishment', title: 'Replenishment', fill: 'FFC2410C', numFmt: '#,##0' },
    ]
    const finalColumn = 1 + blocks.length * Math.max(1, sizes.length) + 1
    const lastLetter = sheet.getColumn(finalColumn).letter

    sheet.mergeCells(`A1:${lastLetter}1`)
    sheet.getCell('A1').value = `${style} · Inventory & Replenishment Plan`
    sheet.getCell('A1').font = { bold: true, size: 16, color: { argb: 'FFFFFFFF' } }
    sheet.getCell('A1').fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1E3A8A' } }
    sheet.getCell('A1').alignment = { vertical: 'middle', horizontal: 'center' }
    sheet.getRow(1).height = 28

    sheet.mergeCells(`A2:${lastLetter}2`)
    sheet.getCell('A2').value = `Inventory as of ${report.reportDate} · Yesterday activity: ${report.movementDay} · Target: previous 30 calendar days' average sales × ${COVERAGE_DAYS} days`
    sheet.getCell('A2').font = { color: { argb: 'FF475569' }, italic: true }
    sheet.getCell('A2').alignment = { horizontal: 'center' }

    const legendSplit = Math.max(2, Math.floor(finalColumn / 2))
    sheet.mergeCells(3, 1, 3, legendSplit)
    sheet.getCell('A3').value = `Yellow inventory: below ${LOW_STOCK_THRESHOLD}`
    sheet.getCell('A3').fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFF2CC' } }
    sheet.mergeCells(3, legendSplit + 1, 3, finalColumn)
    const redLegend = sheet.getCell(3, legendSplit + 1)
    redLegend.value = `Red inventory: below ${CRITICAL_STOCK_THRESHOLD}`
    redLegend.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF4CCCC' } }
    for (const cell of [sheet.getCell('A3'), redLegend]) {
      cell.font = { bold: true, color: { argb: 'FF7C2D12' } }
      cell.alignment = { horizontal: 'center' }
    }

    sheet.mergeCells('A4:A5')
    sheet.getCell('A4').value = 'Color'
    sheet.getCell('A4').fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0F172A' } }
    sheet.getCell('A4').font = { bold: true, color: { argb: 'FFFFFFFF' } }
    sheet.getCell('A4').alignment = { horizontal: 'center', vertical: 'middle' }
    let column = 2
    const blockStarts = {}
    for (const block of blocks) {
      const start = column
      const end = column + Math.max(1, sizes.length) - 1
      blockStarts[block.key] = start
      if (end > start) sheet.mergeCells(4, start, 4, end)
      const groupHeader = sheet.getCell(4, start)
      groupHeader.value = block.title
      groupHeader.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: block.fill } }
      groupHeader.font = { bold: true, color: { argb: 'FFFFFFFF' } }
      groupHeader.alignment = { horizontal: 'center', vertical: 'middle' }
      for (let index = 0; index < Math.max(1, sizes.length); index += 1) {
        const sizeHeader = sheet.getCell(5, start + index)
        sizeHeader.value = sizes[index] || '—'
        sizeHeader.fill = {
          type: 'pattern', pattern: 'solid', fgColor: { argb: sizeHeaderFill(sizes[index]) },
        }
        sizeHeader.font = { bold: true, color: { argb: 'FFFFFFFF' } }
        sizeHeader.alignment = { horizontal: 'center', vertical: 'middle' }
      }
      column = end + 1
    }
    sheet.mergeCells(4, finalColumn, 5, finalColumn)
    sheet.getCell(4, finalColumn).value = 'Total Replenishment'
    sheet.getCell(4, finalColumn).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF9A3412' } }
    sheet.getCell(4, finalColumn).font = { bold: true, color: { argb: 'FFFFFFFF' } }
    sheet.getCell(4, finalColumn).alignment = { horizontal: 'center', vertical: 'middle', wrapText: true }

    const firstDataRow = 6
    colors.forEach((colorGroup, colorIndex) => {
      const rowNumber = firstDataRow + colorIndex
      const excelRow = sheet.getRow(rowNumber)
      excelRow.getCell(1).value = colorGroup.color
      excelRow.getCell(1).alignment = { vertical: 'middle' }
      blocks.forEach((block) => {
        sizes.forEach((size, sizeIndex) => {
          const item = colorGroup.bySize.get(size)
          const cell = excelRow.getCell(blockStarts[block.key] + sizeIndex)
          if (!item) {
            cell.value = null
            return
          }
          const value = Number(item[block.key] || 0)
          if (block.key === 'targetStock') {
            const averageLetter = sheet.getColumn(blockStarts.dailyAverage + sizeIndex).letter
            cell.value = { formula: `ROUNDUP(${averageLetter}${rowNumber}*${COVERAGE_DAYS},0)`, result: value }
          } else if (block.key === 'replenishment') {
            const targetLetter = sheet.getColumn(blockStarts.targetStock + sizeIndex).letter
            const inventoryLetter = sheet.getColumn(blockStarts.quantity + sizeIndex).letter
            cell.value = { formula: `MAX(0,${targetLetter}${rowNumber}-${inventoryLetter}${rowNumber})`, result: value }
          } else {
            cell.value = value
          }
          cell.numFmt = block.numFmt
          cell.alignment = { horizontal: 'right', vertical: 'middle' }
          if (block.key === 'quantity') {
            if (value < CRITICAL_STOCK_THRESHOLD) {
              cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF4CCCC' } }
              cell.font = { bold: true, color: { argb: 'FF991B1B' } }
            } else if (value < LOW_STOCK_THRESHOLD) {
              cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFF2CC' } }
              cell.font = { bold: true, color: { argb: 'FF92400E' } }
            }
          } else if (block.key === 'replenishment' && value > 0) {
            cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFDBEAFE' } }
            cell.font = { bold: true, color: { argb: 'FF1E3A8A' } }
          }
        })
      })
      const firstReplenishment = sheet.getColumn(blockStarts.replenishment).letter
      const lastReplenishment = sheet.getColumn(blockStarts.replenishment + sizes.length - 1).letter
      const replenishmentTotal = sizes.reduce((sum, size) =>
        sum + Number(colorGroup.bySize.get(size)?.replenishment || 0), 0)
      excelRow.getCell(finalColumn).value = {
        formula: `SUM(${firstReplenishment}${rowNumber}:${lastReplenishment}${rowNumber})`,
        result: replenishmentTotal,
      }
      excelRow.getCell(finalColumn).numFmt = '#,##0'
      excelRow.getCell(finalColumn).font = { bold: true }
    })

    const totalRowNumber = firstDataRow + colors.length
    const totalRow = sheet.getRow(totalRowNumber)
    totalRow.getCell(1).value = 'TOTAL'
    for (let col = 2; col <= finalColumn; col += 1) {
      const letter = sheet.getColumn(col).letter
      const values = []
      for (let rowNumber = firstDataRow; rowNumber < totalRowNumber; rowNumber += 1) {
        const raw = sheet.getCell(rowNumber, col).value
        values.push(Number(raw && typeof raw === 'object' && 'result' in raw ? raw.result : raw) || 0)
      }
      totalRow.getCell(col).value = {
        formula: `SUM(${letter}${firstDataRow}:${letter}${totalRowNumber - 1})`,
        result: values.reduce((sum, value) => sum + value, 0),
      }
      totalRow.getCell(col).numFmt = blocks.some((block) =>
        block.key === 'dailyAverage' && col >= blockStarts[block.key]
          && col < blockStarts[block.key] + sizes.length
      ) ? '0.0' : '#,##0'
    }
    totalRow.font = { bold: true }
    totalRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFDBEAFE' } }
    totalRow.eachCell((cell) => { cell.border = { top: { style: 'medium', color: { argb: 'FF2563EB' } } } })

    sheet.getColumn(1).width = 28
    for (let col = 2; col < finalColumn; col += 1) sheet.getColumn(col).width = 11
    sheet.getColumn(finalColumn).width = 18
    sheet.getRow(4).height = 24
    sheet.getRow(5).height = 22
    for (let rowNumber = 4; rowNumber <= totalRowNumber; rowNumber += 1) {
      for (let col = 1; col <= finalColumn; col += 1) {
        const cell = sheet.getCell(rowNumber, col)
        cell.border = {
          top: { style: 'thin', color: { argb: 'FFD1D5DB' } },
          left: { style: 'thin', color: { argb: 'FFD1D5DB' } },
          bottom: { style: 'thin', color: { argb: 'FFD1D5DB' } },
          right: { style: 'thin', color: { argb: 'FFD1D5DB' } },
        }
      }
    }
    sheet.pageSetup.printArea = `A1:${lastLetter}${totalRowNumber}`
  }

  if (!workbook.worksheets.length) {
    const sheet = workbook.addWorksheet('Inventory')
    sheet.addRow(['No inventory rows found for the selected styles.'])
  }
  return workbook.xlsx.writeBuffer()
}

module.exports = { buildInventoryEmail, buildInventoryWorkbook, localDateParts, normalizeSettings, previousDate, shouldSendDailyReport }
