const MAX_RECIPIENTS = 20
const MAX_STYLES = 100

function cleanList(value, maxItems, maxLength) {
  const items = Array.isArray(value) ? value : String(value || '').split(/[\n,;]+/)
  return [...new Set(items.map((item) => String(item || '').trim()).filter(Boolean))]
    .slice(0, maxItems)
    .map((item) => item.slice(0, maxLength))
}

function normalizeSettings(input = {}) {
  const recipients = cleanList(input.recipients, MAX_RECIPIENTS, 254).map((email) => email.toLowerCase())
  const invalidEmail = recipients.find((email) => !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))
  if (invalidEmail) throw new Error(`Invalid email address: ${invalidEmail}`)
  const styles = cleanList(input.styles, MAX_STYLES, 100).map((style) => style.toUpperCase())
  const sendHour = Number(input.sendHour ?? input.send_hour ?? 9)
  if (!Number.isInteger(sendHour) || sendHour < 0 || sendHour > 23) throw new Error('Send hour must be from 0 to 23')
  return {
    enabled: Boolean(input.enabled),
    recipients,
    styles,
    sendHour,
    timezone: 'America/New_York',
  }
}

function localDateParts(now = new Date(), timezone = 'America/New_York') {
  const parts = Object.fromEntries(new Intl.DateTimeFormat('en-CA', {
    timeZone: timezone,
    year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit',
    hourCycle: 'h23',
  }).formatToParts(now).filter((part) => part.type !== 'literal').map((part) => [part.type, part.value]))
  return { date: `${parts.year}-${parts.month}-${parts.day}`, hour: Number(parts.hour) }
}

function previousDate(date) {
  const value = new Date(`${date}T12:00:00Z`)
  value.setUTCDate(value.getUTCDate() - 1)
  return value.toISOString().slice(0, 10)
}

function escapeHtml(value) {
  return String(value ?? '').replace(/[&<>"']/g, (char) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  })[char])
}

function buildInventoryEmail({ reportDate, inventory = [], movements = [] }) {
  const movementMap = new Map(movements.map((row) => [
    `${row.style}\u241f${row.color}\u241f${row.size}`,
    { sales: Number(row.sales || 0), returns: Number(row.returns || 0) },
  ]))
  const rows = inventory.map((row) => {
    const movement = movementMap.get(`${row.style}\u241f${row.color}\u241f${row.size}`) || { sales: 0, returns: 0 }
    return { ...row, quantity: Number(row.quantity || 0), ...movement, net: movement.returns - movement.sales }
  })
  const totals = rows.reduce((sum, row) => ({
    quantity: sum.quantity + row.quantity,
    sales: sum.sales + row.sales,
    returns: sum.returns + row.returns,
    net: sum.net + row.net,
  }), { quantity: 0, sales: 0, returns: 0, net: 0 })
  const bodyRows = rows.map((row) => `<tr><td>${escapeHtml(row.style)}</td><td>${escapeHtml(row.color)}</td><td>${escapeHtml(row.size)}</td><td>${row.quantity}</td><td>${row.sales}</td><td>${row.returns}</td><td>${row.net > 0 ? '+' : ''}${row.net}</td></tr>`).join('')
  const html = `<!doctype html><html><body style="font-family:Arial,sans-serif;color:#172033"><h2>Daily Inventory Update · ${escapeHtml(reportDate)}</h2><p>Current stock with the previous day's sales and returns.</p><table style="border-collapse:collapse;width:100%;font-size:14px"><thead><tr style="background:#eef2ff"><th>Style</th><th>Color</th><th>Size</th><th>On hand</th><th>Sales</th><th>Returns</th><th>Net</th></tr></thead><tbody>${bodyRows || '<tr><td colspan="7">No inventory rows found.</td></tr>'}</tbody><tfoot><tr style="font-weight:bold;background:#f8fafc"><td colspan="3">Total</td><td>${totals.quantity}</td><td>${totals.sales}</td><td>${totals.returns}</td><td>${totals.net > 0 ? '+' : ''}${totals.net}</td></tr></tfoot></table><p style="color:#64748b;font-size:12px">Generated by Feiya ERP.</p><style>th,td{border:1px solid #dbe2ea;padding:8px;text-align:left}th{white-space:nowrap}</style></body></html>`
  return { rows, totals, html, subject: `Daily Inventory Update · ${reportDate}` }
}

module.exports = { buildInventoryEmail, localDateParts, normalizeSettings, previousDate }
