const MAX_RECIPIENTS = 20
const MAX_STYLES = 100
const LOW_STOCK_THRESHOLD = 50
const CRITICAL_STOCK_THRESHOLD = 20

function cleanList(value, maxItems, maxLength) {
  const items = Array.isArray(value) ? value : String(value || '').split(/[\n,;]+/)
  return [...new Set(items.map((item) => String(item || '').trim()).filter(Boolean))]
    .slice(0, maxItems)
    .map((item) => item.slice(0, maxLength))
}

function normalizeSettings(input = {}) {
  const recipients = cleanList(input.recipients, MAX_RECIPIENTS, 254).map((email) => email.toLowerCase())
  const invalidEmail = recipients.find((email) => !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))
  if (invalidEmail) throw new Error(`Invalid email address: ${invalidEmail}`)
  const styles = cleanList(input.styles, MAX_STYLES, 100).map((style) => style.toUpperCase())
  const sendHour = Number(input.sendHour ?? input.send_hour ?? 9)
  if (!Number.isInteger(sendHour) || sendHour < 0 || sendHour > 23) throw new Error('Send hour must be from 0 to 23')
  return {
    enabled: Boolean(input.enabled),
    recipients,
    styles,
    sendHour,
    timezone: 'America/New_York',
  }
}

function localDateParts(now = new Date(), timezone = 'America/New_York') {
  const parts = Object.fromEntries(new Intl.DateTimeFormat('en-CA', {
    timeZone: timezone,
    year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit',
    hourCycle: 'h23',
  }).formatToParts(now).filter((part) => part.type !== 'literal').map((part) => [part.type, part.value]))
  return { date: `${parts.year}-${parts.month}-${parts.day}`, hour: Number(parts.hour) }
}

function previousDate(date) {
  const value = new Date(`${date}T12:00:00Z`)
  value.setUTCDate(value.getUTCDate() - 1)
  return value.toISOString().slice(0, 10)
}

function escapeHtml(value) {
  return String(value ?? '').replace(/[&<>"']/g, (char) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  })[char])
}

function buildInventoryEmail({ reportDate, inventory = [], movements = [] }) {
  const movementMap = new Map(movements.map((row) => [
    `${row.style}\u241f${row.color}\u241f${row.size}`,
    { sales: Number(row.sales || 0), returns: Number(row.returns || 0) },
  ]))
  const rows = inventory.map((row) => {
    const movement = movementMap.get(`${row.style}\u241f${row.color}\u241f${row.size}`) || { sales: 0, returns: 0 }
    return { ...row, quantity: Number(row.quantity || 0), ...movement, net: movement.returns - movement.sales }
  })
  const totals = rows.reduce((sum, row) => ({
    quantity: sum.quantity + row.quantity,
    sales: sum.sales + row.sales,
    returns: sum.returns + row.returns,
    net: sum.net + row.net,
  }), { quantity: 0, sales: 0, returns: 0, net: 0 })
  const bodyRows = rows.map((row) => `<tr><td>${escapeHtml(row.style)}</td><td>${escapeHtml(row.color)}</td><td>${escapeHtml(row.size)}</td><td>${row.quantity}</td><td>${row.sales}</td><td>${row.returns}</td><td>${row.net > 0 ? '+' : ''}${row.net}</td></tr>`).join('')
  const html = `<!doctype html><html><body style="font-family:Arial,sans-serif;color:#172033"><h2>Daily Inventory Update · ${escapeHtml(reportDate)}</h2><p>Current stock with the previous day's sales and returns.</p><table style="border-collapse:collapse;width:100%;font-size:14px"><thead><tr style="background:#eef2ff"><th>Style</th><th>Color</th><th>Size</th><th>On hand</th><th>Sales</th><th>Returns</th><th>Net</th></tr></thead><tbody>${bodyRows || '<tr><td colspan="7">No inventory rows found.</td></tr>'}</tbody><tfoot><tr style="font-weight:bold;background:#f8fafc"><td colspan="3">Total</td><td>${totals.quantity}</td><td>${totals.sales}</td><td>${totals.returns}</td><td>${totals.net > 0 ? '+' : ''}${totals.net}</td></tr></tfoot></table><p style="color:#64748b;font-size:12px">Generated by Feiya ERP.</p><style>th,td{border:1px solid #dbe2ea;padding:8px;text-align:left}th{white-space:nowrap}</style></body></html>`
  return { rows, totals, html, subject: `Daily Inventory Update · ${reportDate}` }
}

function safeSheetName(value, usedNames) {
  const base = String(value || 'Style').replace(/[\\/?*[\]:]/g, ' ').replace(/\s+/g, ' ').trim().slice(0, 31) || 'Style'
  let name = base
  let suffix = 2
  while (usedNames.has(name.toLowerCase())) {
    const ending = ` (${suffix++})`
    name = `${base.slice(0, 31 - ending.length)}${ending}`
  }
  usedNames.add(name.toLowerCase())
  return name
}

async function buildInventoryWorkbook(report) {
  const ExcelJS = require('exceljs')
  const workbook = new ExcelJS.Workbook()
  workbook.creator = 'Feiya ERP'
  workbook.created = new Date(`${report.reportDate || new Date().toISOString().slice(0, 10)}T12:00:00Z`)

  const rowsByStyle = new Map()
  for (const row of report.rows || []) {
    const style = String(row.style || '').trim() || 'Unknown Style'
    if (!rowsByStyle.has(style)) rowsByStyle.set(style, [])
    rowsByStyle.get(style).push(row)
  }

  const usedNames = new Set()
  for (const [style, rows] of rowsByStyle) {
    const sheet = workbook.addWorksheet(safeSheetName(style, usedNames), {
      views: [{ state: 'frozen', ySplit: 4 }],
      pageSetup: { orientation: 'landscape', fitToPage: true, fitToWidth: 1, fitToHeight: 0 },
    })
    sheet.mergeCells('A1:F1')
    sheet.getCell('A1').value = `${style} · Daily Inventory Update`
    sheet.getCell('A1').font = { bold: true, size: 16, color: { argb: 'FFFFFFFF' } }
    sheet.getCell('A1').fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1E3A8A' } }
    sheet.getCell('A1').alignment = { vertical: 'middle', horizontal: 'center' }
    sheet.getRow(1).height = 28

    sheet.mergeCells('A2:F2')
    sheet.getCell('A2').value = `Inventory as of ${report.reportDate} · Activity from ${report.movementDay}`
    sheet.getCell('A2').font = { color: { argb: 'FF475569' }, italic: true }
    sheet.getCell('A2').alignment = { horizontal: 'center' }

    sheet.mergeCells('A3:C3')
    sheet.getCell('A3').value = `Yellow: below ${LOW_STOCK_THRESHOLD}`
    sheet.getCell('A3').fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFF2CC' } }
    sheet.mergeCells('D3:F3')
    sheet.getCell('D3').value = `Red: below ${CRITICAL_STOCK_THRESHOLD}`
    sheet.getCell('D3').fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF4CCCC' } }
    for (const cell of ['A3', 'D3']) {
      sheet.getCell(cell).font = { bold: true, color: { argb: 'FF7C2D12' } }
      sheet.getCell(cell).alignment = { horizontal: 'center' }
    }

    const header = sheet.addRow(['Color', 'Size', 'On Hand', 'Yesterday Sales', 'Yesterday Returns', 'Net Change'])
    header.font = { bold: true, color: { argb: 'FFFFFFFF' } }
    header.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF2563EB' } }
    header.alignment = { horizontal: 'center', vertical: 'middle' }
    header.height = 24

    for (const item of rows) {
      const row = sheet.addRow([item.color, item.size, item.quantity, item.sales, item.returns, item.net])
      row.getCell(3).numFmt = '#,##0'
      row.getCell(4).numFmt = '#,##0'
      row.getCell(5).numFmt = '#,##0'
      row.getCell(6).numFmt = '+#,##0;-#,##0;0'
      if (item.quantity < CRITICAL_STOCK_THRESHOLD) {
        row.getCell(3).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF4CCCC' } }
        row.getCell(3).font = { bold: true, color: { argb: 'FF991B1B' } }
      } else if (item.quantity < LOW_STOCK_THRESHOLD) {
        row.getCell(3).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFF2CC' } }
        row.getCell(3).font = { bold: true, color: { argb: 'FF92400E' } }
      }
    }

    const total = rows.reduce((sum, row) => ({
      quantity: sum.quantity + row.quantity,
      sales: sum.sales + row.sales,
      returns: sum.returns + row.returns,
      net: sum.net + row.net,
    }), { quantity: 0, sales: 0, returns: 0, net: 0 })
    const totalRow = sheet.addRow(['TOTAL', '', total.quantity, total.sales, total.returns, total.net])
    totalRow.font = { bold: true }
    totalRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFDBEAFE' } }
    totalRow.eachCell((cell) => { cell.border = { top: { style: 'medium', color: { argb: 'FF2563EB' } } } })
    totalRow.getCell(6).numFmt = '+#,##0;-#,##0;0'

    sheet.autoFilter = { from: 'A4', to: `F${Math.max(4, sheet.rowCount - 1)}` }
    sheet.columns = [
      { width: 26 }, { width: 14 }, { width: 14 }, { width: 18 }, { width: 20 }, { width: 16 },
    ]
    for (let rowNumber = 4; rowNumber <= sheet.rowCount; rowNumber += 1) {
      const row = sheet.getRow(rowNumber)
      row.alignment = { vertical: 'middle' }
      for (let column = 3; column <= 6; column += 1) row.getCell(column).alignment = { horizontal: 'right', vertical: 'middle' }
    }
  }

  if (!workbook.worksheets.length) {
    const sheet = workbook.addWorksheet('Inventory')
    sheet.addRow(['No inventory rows found for the selected styles.'])
  }
  return workbook.xlsx.writeBuffer()
}

module.exports = { buildInventoryEmail, buildInventoryWorkbook, localDateParts, normalizeSettings, previousDate }
